import Head from "next/head";
import Hero from "../components/Hero";
import React from "react";
import Shop from "../components/Shop";

const Work = () => {
  return (
    <div>
      <Head>
        <title>Photography Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        heading="My Shop"
        message="This is some of my recent work traveling the world."
      />
      <Shop />
    </div>
  );
};

export default Work;
